features for search and get stackbuilders youtube videos
ferjozsot23/stack_yt_videos_api pull request #2
Opened 2024-04-05 17:36 UTC by ferjozsot23

2024-04-10 14:15 UTC, CristopherDavid requested changes
Great work overall, there are room for improvement. left some comments

2024-04-10 14:15 UTC, CristopherDavid commented on test/test.js
> +})
I would like to suggest to use BDD here, so let's add a second internal describe, which contain the scenario. For Example
```
describe("getTopLikedVideos",() => {
    describe("when it receives an empty array, ()=>{
     // Write the test cases here
     }
    describe("when it receives an array with less than 5 elements, ()=>{
     // Write the test cases here
     }
     describe("when it receives an array of elements, ()=>{
     // Write the test cases here
     }
})
```

This way you cover more cases and your tests become more descriptive, you can also use https://betterspecs.org/ as style guide

2024-04-10 14:15 UTC, CristopherDavid commented on test/test.js
> +    it("should return the total number of likes of all videos", function () {
use arrow functions here

2024-04-10 14:47 UTC, dalejo96 requested changes

2024-04-10 14:47 UTC, dalejo96 commented on src/api/client.js
> +const api_key = api_key_secret
Why `api_key_secret` and `api_key` if it is the same thing?

2024-04-10 14:47 UTC, dalejo96 commented on src/search/videoId.js
> +            videoDuration: "any",
Maybe create some constants here

2024-04-10 14:47 UTC, dalejo96 commented on src/search/videoId.js
> +        return []
let's throw an error instead of returning an empty list.

2024-04-10 14:47 UTC, dalejo96 commented on src/search/videoMetadata.js
> +        return []
Same here

2024-04-10 14:47 UTC, dalejo96 commented on test/test.js
> +        const result = getTopLikedVideos(fixtureData)
What about `null` and `undefined`?
For all the functions.

2024-04-16 15:05 UTC, dalejo96 approved these changes
This is looking great! Good job and test coverage.
We have to check the error handling workflow, but so far so good, let's bring some questions to the catch-up tomorrow.

2024-04-16 15:05 UTC, dalejo96 commented on src/search/videoMetadata.js
> +            ({ id, snippet, statistics }) => ({
:+1:

2024-04-16 15:05 UTC, dalejo96 commented on src/search/videoMetadata.js
> +    const videosIdArray = await getVideosId()
Why this is outside the try/catch block?

2024-04-16 15:05 UTC, dalejo96 commented on index.js
> +const stackbuildersVideoData = await getVideosMetadata()
What if this one fails?

2024-04-22 16:12 UTC, CristopherDavid requested changes
Good job, we still have room for improvement

2024-04-22 16:12 UTC, CristopherDavid commented on src/calculation/calculation.js
> +              .slice(0, 5)
instead of doing the validations directly inside of every function, let's create a validation function that checks if the data has the correct format, if it's not null or undefined, and if it's not empty. Validate the data and then if it's valid use it in this functions. That way we separate concerns, keep the functions atomic and avoid unnecessary code repetition

2024-04-22 16:12 UTC, CristopherDavid commented on src/search/videoId.js
> +async function getVideosId() {
I think it's still a good idea to give this function a more descriptive name

2024-04-22 16:12 UTC, CristopherDavid commented on src/search/videoId.js
> +    }
This has multiple ways to fail. IE: The API is not sending anything, The format of the info changed. Let's handle errors in a way we cover the possible scenarios, the error is not descriptive of what's happening

2024-04-22 16:12 UTC, CristopherDavid commented on src/search/videoMetadata.js
> +}
Improve error handling, at least make it so the user can actually identify what and where it's failing

2024-04-22 16:12 UTC, CristopherDavid commented on test/fixtures/youtubeData.js
> +export default fixtureData
Hmmm I saw this exports default in multiple places and some of them are unnecessary, you can use just the `export` at the declaration of the const

2024-04-22 16:12 UTC, CristopherDavid commented on test/test.js
> +    })
Same here, why are we returning 0 when this could be an error affecting an app?

2024-04-30 21:37 UTC, CristopherDavid approved these changes
Great work Fernando 🚀

2024-04-30 21:55 UTC, dalejo96 requested changes
Almost ready!
Please resolve the conversations once you create a commit with the requested changes.

2024-04-30 21:55 UTC, dalejo96 commented on src/api/client.js
> +
```suggestion
```

2024-04-30 21:55 UTC, dalejo96 commented on src/calculation/calculation.js
> +        : (() => { throw new Error("Invalid input: Expected an array of videos with its metadata"); })();
This is not great!
Why create an anonymous function and call it immediately?
You can simply throw the error.
Why parsing it?
Why not return an empty array?

2024-04-30 21:55 UTC, dalejo96 commented on src/search/videoId.js
> +            response.data.items.length === 0
You can create a constant for this boolean, use a meaningful name

2024-05-02 21:20 UTC, dalejo96 approved these changes
LGTM!
Just a small comment, do not confuse variables with constants.
But good work so far!

2024-05-02 21:20 UTC, dalejo96 commented on src/search/videoId.js
> +    }
This is just a variable not a constant, so `camelCase` is just fine

2024-05-02 21:24 UTC, merged